services:
  - type: web
    name: bubble-pdf-exporter
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
